version: '3.4'
volumes:
  data:
networks: 
  db_network:
services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      - db_network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    networks:
      - db_network
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
    environment:
      MYSQL_ROOT_PASSWORD: root